### PR TITLE
feat(gzip): allow gzip by default for all requests

### LINKED ISSUE #196: Support gzip compression by default for all requests
### Expected behavior
- All requests should use gzip as default to improve performance

### Actual behavior
- At the moment, no requests sent via the node-sdk are using this, which leads to performance degradation

### Steps to reproduce the behavior
---

### PR DESCRIPTION
**Pull request by wizzy25**
fixes #196

### CODE REVIEW

**Comment by butenkor** [comment]
@hisabimbola I am just curious - why is it a breaking change and why would you do it optional?

**Comment by wizzy25** [comment]
@hisabimbola please review again

**Comment by hisabimbola** [comment]
@butenkor 
> why is it a breaking change
because the new behaviour differs from the previous implementation
> why would you do it optional?
I don't get what you mean by this, but what this PR did was add gzip flag by default and gave option to turn it off if desired...

**Comment by butenkor** [comment]
How functional behaviour is changed if request data to API was not compressed before and now it is?

Why would anyone want to switch it off if it improves transfer speed?

**Comment by hisabimbola** [comment]
@wizzy25 

Let's update this PR to make it enable by default and deploy this as a new feature not ~breaking change~

**Comment by wizzy25** [comment]
It's presently enabled by default @hisabimbola

**Comment by yanns** [comment]
Thx for pushing this!!
It will help a lot, in impex for example.

**Comment by wizzy25** [comment]
@hisabimbola I think the `package.json` files of the modules and impex should be updated after this is released, and possibly added somewhere (release notes?) in impex

**Pull request merged**
