### PR TITLE
fix(productSync): prevent duplicate actions

### PR DESCRIPTION
**Pull request by PhilippSpo**
@emmenko @hajoeichler

### CODE REVIEW

**Comment by emmenko** [comment]
@PhilippSpo what's this for?

**Comment by PhilippSpo** [comment]
@emmenko I will add a test and you will see

**Comment by PhilippSpo** [comment]
@emmenko So the duplicate actions were generated when using the price id for comparing two prices, since it would generate deltas like this one, when you want to replace one price with another:
```coffee
# this delta would break the price import and produce duplicate actions
delta =
  masterVariant:
    prices:
      0: [
        value:
          currencyCode: "EUR"
          centAmount: 200
      ]
      _t: "a"
      _0: [
        value:
          currencyCode: 'US'
          centAmount: 100
      , 0, 0
      ]
```
This generates the following actions:
```js
[ { action: 'removePrice',
    variantId: 1,
    price: { value: [Object] } },
  { action: 'removePrice',
    variantId: 1,
    price: { value: [Object] } },
  { action: 'addPrice', variantId: 1, price: { value: [Object] } },
  { action: 'addPrice', variantId: 1, price: { value: [Object] } } ]
```
Since we decided to not use price.id for comparing after all this is probably irrelevant an can be closed.

**Comment by emmenko** [comment]
Ok

**Pull request closed without merging**
