### PR TITLE
feat(subscriptions): add subscription endpoint

### PR DESCRIPTION
**Pull request by lojzatran**
- [ ] commit messages are commitizen-friendly
- [ ] code is unit tested
- [ ] code is integration tested
- [ ] public code is documented
- [ ] code is reviewed by at least one person
- [ ] code satisfies linter rules

@emmenko @PhilippSpo @butenkor Can you review? This feature is still in testing mode. There's no docs about it. So for now, I just added a class without any comments, so it's possible to test it. Once this feature is released, it can be improved.

### CODE REVIEW

**Comment by emmenko** [comment]
As discussed with @butenkor using this endpoint doesn't necessarily require the SDK, as it's meant to be used like once or twice. Given also that it's not documented and it's still in early development I would not include it in the SDK, yet.
If you want to use it now, simply do it with curl.

**Comment by butenkor** [comment]
@emmenko @PhilippSpo Can we use it as beta feature? I assume nobody will use it if it is not documented yet.

**Comment by mmoelli** [comment]
@butenkor This feature was meant for internal testing only ATM. Please consult with @cneijenhuis @gogregor regarding release procedure.

**Comment by butenkor** [comment]
@mmoelli How harmful is that if it is not documented and would be marked as BETA in code?

**Comment by butenkor** [comment]
@lojzatran will add comment ```"FOR INTERNAL USAGE ONLY AND MAY BE REMOVED ANYTIME!" ```

**Pull request closed without merging**
