### PR TITLE
fix(inventory): change quantity instead of calculating the difference

### PR DESCRIPTION
**Pull request by lojzatran**
The main reason for this change is it's easier to repeat the request in case of concurrent modification error. With the old diff calculation, it's necessary to refetch the inventories and recalculate the diff. With this new change, it's enough to change the version number and repeat the request.

- [ ] commit messages are commitizen-friendly
- [ ] code is unit tested
- [ ] code is integration tested
- [ ] public code is documented
- [ ] code is reviewed by at least one person
- [ ] code satisfies linter rules

### CODE REVIEW

**Comment by Siilwyn** [comment]
This looks almost too good to be true, less code & better functionality. 👀 
There must be a reason why this wasn't done initially though...
Also please check out what's causing the decreased coverage.

**Comment by lojzatran** [comment]
@Siilwyn I think the reason was when node-sdk was created, there was no `changeQuantity` function in the API :)

**Comment by Siilwyn** [comment]
Ah good one, great idea to change it. 👍 🎉

**Comment by lojzatran** [comment]
@Siilwyn coverage is back to normal, I think there was some inconsistencies in coveralls that causes the coverage decrease.

**Comment by Siilwyn** [comment]
It's still decreased, no?

**Comment by lojzatran** [comment]
@Siilwyn ah ok, I looked at it at the wrong time. I'm not sure why the coverage is decreasing as I removed some codes, so it should increase 😕

**Pull request merged**
