### PR TITLE
fix(pagedRequest): set hasUniqueParams option to false

### LINKED ISSUE #117: Only last of multiple query parameters remain in query, in some circumstances.
I created a request using 2 ``expand()`` parameters.

``client.productProjections.staged(true).where(sku in ("some-sku")').expand('masterVariant.prices[*].channel').expand('variants[*].prices[*].channel').all().fetch()``

### Expected behavior
The generated query contains 2 ``expand`` parameters because I called ``.expand()`` twice.

### Actual behavior

The generated query contains only 1 ``expand`` parameter.

### Steps to reproduce the behavior

See above.

Problem does not occur if I use ``.perPage(100)`` instead of ``.all()`` in the query.

Tracing the problem, if I use ``all()``, ``perPage`` is set to 0, the if condition at https://github.com/sphereio/sphere-node-sdk/blob/c75a5ca29121a072f776d7f2e67336ad381f412b/src/coffee/services/base.coffee#L287 evaluates to true (at least in my case...) and ``@_paged()`` is called. 

Inside this method, ``@_rest.PAGED()`` is called, and there ``_.parseQuery()`` is called:
https://github.com/sphereio/sphere-node-sdk/blob/c75a5ca29121a072f776d7f2e67336ad381f412b/src/coffee/connect/rest.coffee#L184
 but without the ``false`` parameter: https://www.npmjs.com/package/underscore-mixins#_parsequery , so the 1st ``expand``parameter disappears.

### PR DESCRIPTION
**Pull request by PhilippSpo**
- [x] commit messages are commitizen-friendly
- [x] code is unit tested
- [x] ~~code is integration tested~~
- [x] public code is documented
- [x] code is reviewed by at least one person
- [x] code satisfies linter rules

so that it is possible to for example expand multiple references

fixes #117

### CODE REVIEW

**Comment by PhilippSpo** [comment]
@emmenko can you hint me to the right place to add tests for this?

**Comment by emmenko** [comment]
@PhilippSpo something like this https://github.com/sphereio/sphere-node-sdk/blob/master/src/spec/client/services/base.spec.coffee#L613-L616

**Comment by PhilippSpo** [comment]
@emmenko That also was my initial idea, but [here](https://github.com/sphereio/sphere-node-sdk/blob/master/src/spec/client/services/base.spec.coffee#L64) the rest is mocked completely. I would have to unit test the rest module itself, not the base service, right?

**Comment by emmenko** [comment]
No, you just want to check the url

**Comment by emmenko** [comment]
```coffeescript
spyOn(@service, '_paged')
@service.all().expand('foo').expand('bar').expand('baz').fetch()
expect(@service._paged).toHaveBeenCalledWith "#{o.path}?limit=0&expand=foo&expand=bar&expand=baz"
```

**Comment by PhilippSpo** [comment]
Nope.. the `_paged` method of the `baseService` was always called with the correct url, but the `PAGED` method of the `rest` module parses this url using `_.parseQuery()` without the hasUniqueParams set to true. Thats why we have to test the `rest` module here.

**Comment by emmenko** [comment]
Ah right :+1:

**Pull request merged**
